
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: LangQuiz
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, metrics
  endpoint:
    health:
      show-details: always
mongock:
  enabled: true
  migration-scan-package: pl.mazak.lquiz.migration
